version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    assignees:
      - michael-doubez
    commit-message:
      prefix: "[deps] "
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    assignees:
      - michael-doubez
    commit-message:
      prefix: "[docker] "
